import Link from "next/link";
import { notFound, redirect } from "next/navigation";

import { defaultRolePermissions, permissionLabels, permissions, roleLabels } from "@/modules/authentication";
import { isAuthError } from "@/modules/authentication/errors";
import { getUserManagementContext, getHospitalUserDetail, listLinkableDoctors } from "@/modules/hospital-administration/server/service";
import { updateRoleAction } from "@/modules/hospital-administration/server/admin-actions";
import { linkDoctorProfileAction, removePermissionOverrideAction, setPermissionOverrideAction, updateMembershipStatusAction } from "@/modules/hospital-administration/server/administration-actions";

export default async function UserDetailPage({ params, searchParams }: { params: Promise<{ membershipId: string }>; searchParams: Promise<{ success?: string; error?: string }> }) {
  const { membershipId } = await params; const query = await searchParams;
  let context; try { context = await getUserManagementContext(); } catch (error) { if (isAuthError(error) && error.status === 401) redirect("/login"); return <p className="rounded-xl border border-red-200 bg-red-50 p-6 text-red-900">Access denied.</p>; }
  let detail; try { detail = await getHospitalUserDetail(context.hospital.id, membershipId); } catch { notFound(); }
  const doctors = await listLinkableDoctors(context.hospital.id);
  const rolePermissions = new Set(defaultRolePermissions[detail.role]);
  const overrides = new Map(detail.overrides.map((item) => [item.permissionCode, item]));
  return <div className="space-y-6"><Link href="/admin/users" className="text-sm font-semibold text-teal-700">← Users &amp; access</Link><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="text-3xl font-semibold">{detail.displayName}</h1><p className="mt-1 text-slate-500">{detail.email}</p><div className="mt-3 flex gap-2 text-sm"><span className="rounded-full bg-teal-50 px-3 py-1 font-semibold text-teal-800">{roleLabels[detail.role]}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-700">{detail.membershipStatus === "active" ? "Active" : "Disabled"}</span></div></div><form action={updateMembershipStatusAction}><input type="hidden" name="hospitalId" value={context.hospital.id}/><input type="hidden" name="membershipId" value={membershipId}/><input type="hidden" name="expectedUpdatedAt" value={detail.updatedAt.toISOString()}/><input type="hidden" name="status" value={detail.membershipStatus === "active" ? "disabled" : "active"}/><button className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold">{detail.membershipStatus === "active" ? "Disable access" : "Reactivate access"}</button></form></header>{query.success ? <p className="rounded-lg border border-green-200 bg-green-50 p-3 text-sm text-green-800">Change saved.</p> : null}
  <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Role and access</h2><form action={updateRoleAction} className="mt-4 flex gap-2"><input type="hidden" name="hospitalId" value={context.hospital.id}/><input type="hidden" name="membershipId" value={membershipId}/><input type="hidden" name="expectedUpdatedAt" value={detail.updatedAt.toISOString()}/><select name="role" defaultValue={detail.role} disabled={detail.role === "platform_admin"} className="flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm">{Object.entries(roleLabels).filter(([role]) => role !== "platform_admin" || detail.role === "platform_admin").map(([role, label]) => <option key={role} value={role}>{label}</option>)}</select><button disabled={detail.role === "platform_admin"} className="rounded-lg bg-teal-700 px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">Change role</button></form><p className="mt-3 text-xs text-slate-500">Published system roles are protected definitions. Individual exceptions are managed below.</p>{detail.role === "doctor" ? <><h3 className="mt-6 font-semibold">Doctor profile</h3><p className="mt-1 text-sm text-slate-500">{detail.doctorLink ? detail.doctorLink.displayName : "No doctor profile linked"}</p><form action={linkDoctorProfileAction} className="mt-3 flex gap-2"><input type="hidden" name="hospitalId" value={context.hospital.id}/><input type="hidden" name="membershipId" value={membershipId}/><select name="doctorId" className="min-w-0 flex-1 rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm"><option value="">Select doctor profile</option>{doctors.map((doctor) => <option key={doctor.id} value={doctor.id}>{doctor.displayName} ({doctor.stableKey})</option>)}</select><button className="rounded-lg border border-slate-300 px-3 py-2 text-sm font-semibold">Link</button></form></> : null}</section>
  <section className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-semibold">Effective permissions</h2><p className="mt-1 text-sm text-slate-500">Inherited role access plus explicit audited overrides.</p><div className="mt-4 space-y-2">{permissions.map((permission) => { const override = overrides.get(permission); const effective = override ? override.granted : rolePermissions.has(permission); return <div key={permission} className="flex items-center justify-between gap-3 rounded-lg bg-slate-50 px-3 py-2 text-sm"><span><span className={effective ? "mr-2 text-teal-700" : "mr-2 text-slate-400"}>{effective ? "✓" : "○"}</span>{permissionLabels[permission]}</span>{override ? <form action={removePermissionOverrideAction}><input type="hidden" name="hospitalId" value={context.hospital.id}/><input type="hidden" name="membershipId" value={membershipId}/><input type="hidden" name="permissionCode" value={permission}/><button className="text-xs font-semibold text-slate-500 underline">Remove override</button></form> : <form action={setPermissionOverrideAction} className="flex items-center gap-1"><input type="hidden" name="hospitalId" value={context.hospital.id}/><input type="hidden" name="membershipId" value={membershipId}/><input type="hidden" name="permissionCode" value={permission}/><input type="hidden" name="granted" value={String(!effective)}/><input type="hidden" name="reason" value="Administrative access review"/><button className="text-xs font-semibold text-teal-700 underline">{effective ? "Deny" : "Grant"}</button></form>}</div>; })}</div></section></div></div>;
}
